/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/src/widgets/icon_data.dart';

class IconsCustomize {
  IconsCustomize._();

  static const _kFontFam = 'AppIcons';
  static const String _kFontPkg = null;


  static const IconData survey_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData networking = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birth_date = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thu_no = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tu_van = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData develop_hover = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phattriencongdong = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mainha = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quatet = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scholarship = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insurance = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ptnghe = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_sign = IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggy_bank = IconData(0xf4d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice_dollar = IconData(0xf571, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_dollar = IconData(0xf651, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_dollar = IconData(0xf653, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel_dollar = IconData(0xf662, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_dollar = IconData(0xf688, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_id_v2 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
